# Generated by Django 2.1.3 on 2018-11-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicform',
            name='checkbox',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='basicform',
            name='message',
            field=models.TextField(default='Your message'),
        ),
    ]
